<style>


 
.sidebar-mini.sidebar-collapse .content-wrapper, .sidebar-mini.sidebar-collapse .right-side, .sidebar-mini.sidebar-collapse .main-footer {
    margin-left: 44px !important;
    z-index: 840;
}


.widget-user-2 .widget-user-username, .widget-user-2 .widget-user-desc {
    margin-left: 5px;
}
 
.btn-success {
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}
 
 
.btn-success {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}
.btn-success:hover {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}

.btn, .chosen-container .chosen-single, .chosen-container .chosen-choices {
    border-radius: 0px !important;
}


.btn.btn-flat {
    border-radius: 0;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    border-width: 3px;
}


.btn-success:hover, .btn-success:active, .btn-success.hover {
    background-color: #3c8dbc;
}

.btn-success.focus, .btn-success:focus {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}

.btn-success.active.focus, .btn-success.active:focus, .btn-success.active:hover, .btn-success:active.focus, .btn-success:active:focus, .btn-success:active:hover, .open>.dropdown-toggle.btn-success.focus, .open>.dropdown-toggle.btn-success:focus, .open>.dropdown-toggle.btn-success:hover {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}



.label {
    display: inline;
    padding: 0.3em 0.6em 0.3em;
    font-size: 75%;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: 0em;
}

 .table-striped>tbody>tr:hover {
  background-color: #e1e1e1;
}
 
 
.table-striped>tbody>tr:hover {
    background-color: #e1e1e1 !important;
}
.label-default {
    padding: 0 1px 0 1px;
    background: #fff0 !important;
}

.content-wrapper {
    content: '';
    position: fixed;
    width: 98vw;
    height: 100vh;
    background-image: url(....//cc-content/themes/cicool/asset/img/header2.jpg);
    background-position: center center;
    background-repeat: no-repeat;
    background-attachment: fixed;
    -webkit-background-size: cover;
    background-size: cover;
}
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>

<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+a', function assets() {
       window.location.href = BASE_URL + '/administrator/Inventory/add';
       return false;
   });

   $('*').bind('keydown', 'Ctrl+f', function assets() {
       $('#sbtn').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
       $('#reset').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+b', function assets() {

       $('#reset').trigger('click');
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<!-- Content Header (Page header) -->
<!-- <section class="content-header">
   <h1>
      <?= cclang('inventory') ?><small><?= cclang('list_all'); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class="active"><?= cclang('inventory') ?></li>
   </ol>
</section> -->
<!-- Main content -->
<section class="content">
   <div class="row" >
      
      <div class="col-md-12">
         <div class="box box-warning">
            <div class="box-body ">
               <!-- Widget: user widget style 1 -->
               <div class="box box-widget widget-user-2">
                  <!-- Add the bg color to the header using any of the bg-* classes -->
                  <div class="widget-user-header ">
                     <div class="row pull-right">
                        <?php is_allowed('inventory_add', function(){?>
                        <a class="btn btn-flat btn-success btn_add_new" id="btn_add_new" title="Add New Chemical  (Ctrl+a)" href="<?=  site_url('administrator/inventory/add'); ?>"><i class="fa fa-plus-square-o" ></i> Add New Chemical</a>
                        <?php }) ?>
                        <?php is_allowed('inventory_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export'); ?> <?= cclang('inventory') ?> " href="<?= site_url('administrator/inventory/export?q='.$this->input->get('q').'&f='.$this->input->get('f')); ?>"><i class="fa fa-file-excel-o" ></i> <?= cclang('export'); ?> XLS</a>
                        <?php }) ?>
						<?php is_allowed('inventory_export', function(){?>
                        <a class="btn btn-flat btn-success" title="<?= cclang('export', 'PDF User'); ?>" href="<?= site_url('administrator/inventory/export_pdf'); ?>"><i class="fa fa-file-pdf-o" ></i> <?= cclang('export', 'PDF'); ?></a>
                        <?php }) ?>
                                             </div>
                     <!-- <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_ASSET; ?>/img/list.png" alt="User Avatar">
                     </div> -->
                     <!-- /.widget-user-image -->
                       <i class="label bg-yellow" style="font-size:17px;"><?= $inventory_counts; ?>  Chemicals</i>  
                     <!--<h5 class="widget-user-desc"><?= cclang('list_all', [cclang('inventory')]); ?>  </h5>-->
                  </div>

                  <form name="form_inventory" id="form_inventory" action="<?= base_url('administrator/inventory/index'); ?>">
                  


                     <!-- /.widget-user -->
                  <div class="row">
                     <div class="col-md-8">
                                                <div class="col-sm-2 padd-left-0 " >
                           <select type="text" class="form-control chosen chosen-select" name="bulk" id="bulk" placeholder="Site Email" >
                                                         <option value="delete">Delete</option>
                                                      </select>
                        </div>
                        <div class="col-sm-2 padd-left-0 ">
                           <button type="button" class="btn btn-flat" name="apply" id="apply" title="<?= cclang('apply_bulk_action'); ?>"><?= cclang('apply_button'); ?></button>
                        </div>
                                                <div class="col-sm-3 padd-left-0  " >
                           <input type="text" class="form-control" name="q" id="filter" placeholder="<?= cclang('filter'); ?>" value="<?= $this->input->get('q'); ?>">
                        </div>
                        <div class="col-sm-3 padd-left-0 " >
                           <select type="text" class="form-control chosen chosen-select" name="f" id="field" >
                              <option value=""><?= cclang('all'); ?></option>
                               <option <?= $this->input->get('f') == 'chemical_code' ? 'selected' :''; ?> value="chemical_code">Chemical Code</option>
                            <option <?= $this->input->get('f') == 'name_of_pure_chemical' ? 'selected' :''; ?> value="name_of_pure_chemical">Name Of Pure Chemical</option>
                            <option <?= $this->input->get('f') == 'chemical_formula' ? 'selected' :''; ?> value="chemical_formula">Chemical Formula</option>
                            <option <?= $this->input->get('f') == 'location' ? 'selected' :''; ?> value="location">Location</option>
                            <option <?= $this->input->get('f') == 'date_registered' ? 'selected' :''; ?> value="date_registered">Date Registered</option>
                            <option <?= $this->input->get('f') == 'registered_by' ? 'selected' :''; ?> value="registered_by">Registered By</option>
                            <option <?= $this->input->get('f') == 'state_of_chemical' ? 'selected' :''; ?> value="state_of_chemical">State Of Chemical</option>
                            <option <?= $this->input->get('f') == 'chemical_color_group' ? 'selected' :''; ?> value="chemical_color_group">Chemical Color Group</option>
                            <option <?= $this->input->get('f') == 'cas_no' ? 'selected' :''; ?> value="cas_no">Cas No</option>
                            <option <?= $this->input->get('f') == 'brand' ? 'selected' :''; ?> value="brand">Brand</option>
                            <option <?= $this->input->get('f') == 'lot_no' ? 'selected' :''; ?> value="lot_no">Lot No</option>
                            <option <?= $this->input->get('f') == 'container' ? 'selected' :''; ?> value="container">Container</option>
                            <option <?= $this->input->get('f') == 'storage_condition' ? 'selected' :''; ?> value="storage_condition">Storage Condition</option>
                            <option <?= $this->input->get('f') == 'original_amount' ? 'selected' :''; ?> value="original_amount">Original Amount</option>
                            <option <?= $this->input->get('f') == 'estimated_current_mount' ? 'selected' :''; ?> value="estimated_current_mount">Estimated Current Mount</option>
                            <option <?= $this->input->get('f') == 'date_of_receipt' ? 'selected' :''; ?> value="date_of_receipt">Date Of Receipt</option>
                            <option <?= $this->input->get('f') == 'received_by' ? 'selected' :''; ?> value="received_by">Received By</option>
                            <option <?= $this->input->get('f') == 'date_of_expiration' ? 'selected' :''; ?> value="date_of_expiration">Date Of Expiration</option> 
                           </select>
                        </div>
                        <div class="col-sm-1 padd-left-0 ">
                           <button type="submit" class="btn btn-flat" name="sbtn" id="sbtn" value="Apply" title="<?= cclang('filter_search'); ?>">
                           Filter
                           </button>
                        </div>
                        <div class="col-sm-1 padd-left-0 ">
                           <a class="btn btn-default btn-flat" name="reset" id="reset" value="Apply" href="<?= base_url('administrator/inventory');?>" title="<?= cclang('reset_filter'); ?>">
                           <i class="fa fa-undo"></i>
                           </a>
                        </div>
                     </div>
                     
                  </div>
                  <div class="table-responsive"> 

                  <br>
                  <table class="table table-bordered table-striped dataTable">
                     <thead>
                        <tr class="">
                                                     <th>
                            <input type="checkbox" class="flat-red toltip" id="check_all" name="check_all" title="check all">
                           </th>
                                                    <th data-field="chemical_code"data-sort="1" data-primary-key="1"> <?= cclang('chemical_code') ?></th>
                           <th data-field="name_of_pure_chemical"data-sort="1" data-primary-key="0"> <?= cclang('name_of_pure_chemical') ?></th>
                           <th data-field="chemical_formula"data-sort="1" data-primary-key="0"> <?= cclang('chemical_formula') ?></th>
                           <th data-field="location"data-sort="1" data-primary-key="0"> <?= cclang('location') ?></th>
                           <th data-field="date_registered"data-sort="1" data-primary-key="0"> <?= cclang('date_registered') ?></th>
                           <th data-field="registered_by"data-sort="1" data-primary-key="0"> <?= cclang('registered_by') ?></th>
                           <th data-field="state_of_chemical"data-sort="1" data-primary-key="0"> <?= cclang('state_of_chemical') ?></th>
                           <th data-field="chemical_color_group"data-sort="1" data-primary-key="0"> <?= cclang('chemical_color_group') ?></th>
                           <th data-field="cas_no"data-sort="1" data-primary-key="0"> <?= cclang('cas_no') ?></th>
                           <th data-field="brand"data-sort="1" data-primary-key="0"> <?= cclang('brand') ?></th>
                           <th data-field="lot_no"data-sort="1" data-primary-key="0"> <?= cclang('lot_no') ?></th>
                           <th data-field="container"data-sort="1" data-primary-key="0"> <?= cclang('container') ?></th>
                           <th data-field="storage_condition"data-sort="1" data-primary-key="0"> <?= cclang('storage_condition') ?></th>
                           <th data-field="original_amount"data-sort="1" data-primary-key="0"> <?= cclang('original_amount') ?></th>
                           <th data-field="estimated_current_mount"data-sort="1" data-primary-key="0"> <?= cclang('estimated_current_mount') ?></th>
                           <th data-field="date_of_receipt"data-sort="1" data-primary-key="0"> <?= cclang('date_of_receipt') ?></th>
                           <th data-field="received_by"data-sort="1" data-primary-key="0"> <?= cclang('received_by') ?></th>
                           <th data-field="date_of_expiration"data-sort="1" data-primary-key="0"> <?= cclang('date_of_expiration') ?></th>
						   <th data-field="status"data-sort="1" data-primary-key="0"> <?= cclang('status') ?></th>
                           <th>Action</th>                        </tr>
                     </thead>
                     <tbody id="tbody_inventory">
                     <?php foreach($inventorys as $inventory): ?>
                        <tr>
                                                       <td width="5">
                              <input type="checkbox" class="flat-red check" name="id[]" value="<?= $inventory->chemical_code; ?>">
                           </td>
                           <td><span class="list_group-chemical_code"><?= _ent($inventory->chemical_code); ?></span></td> 
                           <td><span class="list_group-name_of_pure_chemical"><?= _ent($inventory->name_of_pure_chemical); ?></span></td> 
                           <td><span class="list_group-chemical_formula"><?= _ent($inventory->chemical_formula); ?></span></td> 
                           <td><span class="list_group-location"><?= _ent($inventory->location); ?></span></td> 
                           <td><span class="list_group-date_registered"><?= _ent($inventory->date_registered); ?></span></td> 
                           <td><span class="list_group-registered_by"><?= _ent($inventory->registered_by); ?></span></td> 
                           <td><span class="list_group-state_of_chemical"><?= _ent($inventory->state_of_chemical); ?></span></td> 
                           <td><span class="list_group-chemical_color_group"><?= _ent($inventory->chemical_color_group); ?></span></td> 
                           <td><span class="list_group-cas_no"><?= _ent($inventory->cas_no); ?></span></td> 
                           <td><span class="list_group-brand"><?= _ent($inventory->brand); ?></span></td> 
                           <td><span class="list_group-lot_no"><?= _ent($inventory->lot_no); ?></span></td> 
                           <td><span class="list_group-container"><?= _ent($inventory->container); ?></span></td> 
                           <td><span class="list_group-storage_condition"><?= _ent($inventory->storage_condition); ?></span></td> 
                           <td><span class="list_group-original_amount"><?= _ent($inventory->original_amount); ?></span></td> 
                           <td><span class="list_group-estimated_current_mount"><?= _ent($inventory->estimated_current_mount); ?></span></td> 
                           <td><span class="list_group-date_of_receipt"><?= _ent($inventory->date_of_receipt); ?></span></td> 
                           <td><span class="list_group-received_by"><?= _ent($inventory->received_by); ?></span></td> 
                           <td><span class="list_group-date_of_expiration"><?= _ent($inventory->date_of_expiration); ?></span></td>
						   
						   
						   <td><span class="status"><?php if(strtotime(date("Y/m/d")) < strtotime($inventory->date_of_expiration)) 
							echo '<div class="tr" style="color:#fff;text-align:center;font-weight: bold;background-color: #59b159; border-radius: 5em;">&nbsp;&nbsp;Active&nbsp;&nbsp;</div>'; 
						    else { 
							echo '<div style="color:#fff;text-align:center;font-weight: bold;background-color: #ed4346; border-radius: 5em;">&nbsp;&nbsp;&nbsp;Expired&nbsp;&nbsp;&nbsp;</div>';} ?>
						   </span></td>
								
	  
	  
                           <td width="200">
                            
                                                              <?php is_allowed('inventory_view', function() use ($inventory){?>
                                                              <a href="<?= site_url('administrator/inventory/view/' . $inventory->chemical_code); ?>" class="label-default"><i class="fa fa-newspaper-o"></i> <?= cclang('view_button'); ?>
                              <?php }) ?>
                              <?php is_allowed('inventory_update', function() use ($inventory){?>
                              <a href="<?= site_url('administrator/inventory/edit/' . $inventory->chemical_code); ?>" class="label-default"><i class="fa fa-edit "></i> <?= cclang('update_button'); ?></a>
                              <?php }) ?>
                              <?php is_allowed('inventory_delete', function() use ($inventory){?>
                              <a href="javascript:void(0);" data-href="<?= site_url('administrator/inventory/delete/' . $inventory->chemical_code); ?>" class="label-default remove-data"><i class="fa fa-close"></i> <?= cclang('remove_button'); ?></a>
                               <?php }) ?>

                           </td>                        </tr>
                      <?php endforeach; ?>
                      <?php if ($inventory_counts == 0) :?>
                         <tr>
                           <td colspan="100">
                           Inventory data is not available
                           </td>
                         </tr>
                      <?php endif; ?>

                     </tbody>
                  </table>
				  
                  </div>
               </div>
               <hr>
             <div >
                        <div class="dataTables_paginate paging_simple_numbers pull-right" id="example2_paginate" >
                           <?= $pagination; ?>
                        </div>
                     </div>
            </div>
            </form>            
            <!--/box body -->
         </div>
         <!--/box -->
      </div>
   </div>
</section>
<!-- /.content -->

<!-- Page script -->

<script>
  $(document).ready(function(){
   
    (function(){

})()
      
      
      $('.table tbody tr').each(function(){
         var row = $(this);
         (function(){
    var chemical_code = row.find('.list_group-chemical_code');
    var name_of_pure_chemical = row.find('.list_group-name_of_pure_chemical');
    var chemical_formula = row.find('.list_group-chemical_formula');
    var location = row.find('.list_group-location');
    var date_registered = row.find('.list_group-date_registered');
    var registered_by = row.find('.list_group-registered_by');
    var state_of_chemical = row.find('.list_group-state_of_chemical');
    var chemical_color_group = row.find('.list_group-chemical_color_group');
    var cas_no = row.find('.list_group-cas_no');
    var brand = row.find('.list_group-brand');
    var lot_no = row.find('.list_group-lot_no');
    var container = row.find('.list_group-container');
    var storage_condition = row.find('.list_group-storage_condition');
    var original_amount = row.find('.list_group-original_amount');
    var estimated_current_mount = row.find('.list_group-estimated_current_mount');
    var date_of_receipt = row.find('.list_group-date_of_receipt');
    var received_by = row.find('.list_group-received_by');
    var date_of_expiration = row.find('.list_group-date_of_expiration');

})()
      })
      
    $('.remove-data').click(function(){

      var url = $(this).attr('data-href');

      swal({
          title: "<?= cclang('are_you_sure'); ?>",
          text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
          type: "warning",
          showCancelButton: true,
          confirmButtonColor: "#DD6B55",
          confirmButtonText: "YES",
          cancelButtonText: "NO",
          closeOnConfirm: true,
          closeOnCancel: true
        },
        function(isConfirm){
          if (isConfirm) {
            document.location.href = url;            
          }
        });

      return false;
    });


    $('#apply').click(function(){

      var bulk = $('#bulk');
      var serialize_bulk = $('#form_inventory').serialize();

      if (bulk.val() == 'delete') {
         swal({
            title: "<?= cclang('are_you_sure'); ?>",
            text: "<?= cclang('data_to_be_deleted_can_not_be_restored'); ?>",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "YES",
            cancelButtonText: "NO",
            closeOnConfirm: true,
            closeOnCancel: true
          },
          function(isConfirm){
            if (isConfirm) {
               document.location.href = BASE_URL + '/administrator/inventory/delete?' + serialize_bulk;      
            }
          });

        return false;

      } else if(bulk.val() == '')  {
          swal({
            title: "Upss",
            text: "<?= cclang('please_choose_bulk_action_first'); ?>",
            type: "warning",
            showCancelButton: false,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Okay!",
            closeOnConfirm: true,
            closeOnCancel: true
          });

        return false;
      }

      return false;

    });/*end appliy click*/


    //check all
    var checkAll = $('#check_all');
    var checkboxes = $('input.check');

    checkAll.on('ifChecked ifUnchecked', function(event) {   
        if (event.type == 'ifChecked') {
            checkboxes.iCheck('check');
        } else {
            checkboxes.iCheck('uncheck');
        }
    });

    checkboxes.on('ifChanged', function(event){
        if(checkboxes.filter(':checked').length == checkboxes.length) {
            checkAll.prop('checked', 'checked');
        } else {
            checkAll.removeProp('checked');
        }
        checkAll.iCheck('update');
    });
    initSortable('inventory', $('table.dataTable'));
  }); /*end doc ready*/
</script>