<style>

  .content-wrapper,   .main-footer {
     
   
    background-image: url(../../cc-content/themes/cicool/asset/img/header2.jpg);
}
.box {
    position: relative;
    border-radius: 0px;
    background: rgb(255 255 255 / 20%);
    border-top: 0px solid #d2d6de; 
    margin-bottom: 20px;
    width: 100%;
    box-shadow: 0 1px 1px rgb(0 0 0 / 10%);
}
.sidebar-mini.sidebar-collapse .content-wrapper, .sidebar-mini.sidebar-collapse .right-side, .sidebar-mini.sidebar-collapse .main-footer {
    margin-left: 44px !important;
    z-index: 840;
}
.col-md-7 {
    width: 100.333333333%;
}

.widget-user-2 .widget-user-username, .widget-user-2 .widget-user-desc {
    margin-left: 5px;
}
 
.btn-success {
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}
 
 
.btn-success {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}
.btn-success:hover {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}

.btn, .chosen-container .chosen-single, .chosen-container .chosen-choices {
    border-radius: 0px !important;
}


.btn.btn-flat {
    border-radius: 0;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    border-width: 3px;
}


.btn-success:hover, .btn-success:active, .btn-success.hover {
    background-color: #3c8dbc;
}

.btn-success.focus, .btn-success:focus {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}

.btn-success.active.focus, .btn-success.active:focus, .btn-success.active:hover, .btn-success:active.focus, .btn-success:active:focus, .btn-success:active:hover, .open>.dropdown-toggle.btn-success.focus, .open>.dropdown-toggle.btn-success:focus, .open>.dropdown-toggle.btn-success:hover {
    color: #fff;
    background-color: #3c8dbc;
    border-color: #3c8dbc;
}



.label {
    display: inline;
    padding: 0.3em 0.6em 0.3em;
    font-size: 75%;
    font-weight: 700;
    line-height: 1;
    color: #fff;
    text-align: center;
    white-space: nowrap;
    vertical-align: baseline;
    border-radius: 0em;
}

 .table-striped>tbody>tr:hover {
  background-color: #e1e1e1;
}
 
 
.table-striped>tbody>tr:hover {
    background-color: #e1e1e1 !important;
}
.label-default {
    padding: 0 1px 0 1px;
    background: #fff0 !important;
}



.widget-user .widget-user-header {
    padding: 20px;
    height: 218px;
    border-top-right-radius: 3px;
    border-top-left-radius: 3px;
}

 
</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      window.location.href = BASE_URL + '/administrator/user';
       return false;
   });
    
}


jQuery(document).ready(domo);
</script>
<style type="text/css">
  .widget-user-header {
    padding-left: 20px !important; 
  }
</style>
<!-- Content Header (Page header) -->
<!-- <section class="content-header">
   <h1>
      User
      <small>Profile User</small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
      <li class=""><a  href="<?= site_url('administrator/user'); ?>">User</a></li>
      <li class="active">Profile</li>
   </ol>
</section>
<!-- Main content -->
<section class="content">
   <div class="row" >
     
      <div class="col-md-7">
         <div class="box box-warning">
            <div class="box-body ">

                   <!-- /.col -->
                  <div class="col-md-12"><br>
                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user" >
                      <!-- Add the bg color to the header using any of the bg-* classes -->
					  
                      <div class="widget-user-header ">
                        <h3 class="widget-user-username text-white"><?= _ent(ucwords($user->full_name)); ?></h3>
                        <h5 class="widget-user-desc text-white"><?= _ent($user->username); ?></h5>
                      </div>
                      <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_URL.'uploads/user/'.(!empty($user->avatar) ? $user->avatar :'default.png'); ?>" alt="User Avatar" style="height: 80px; width: 80px" >
                      </div>
                      <div>
                       
                        <!-- /.row -->
                      </div>
                    </div>     
                    </div>
                    <div class="col-md-6">
                      <!-- Widget: user widget style 1 -->
                      <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="">
                          <br>
                          <h3 style="color: white;"> &nbsp;&nbsp;Group User</h3>
						  <br>
                        </div>
                        <div class="box-footer no-padding">
                          <ul class="nav nav-stacked">
                          <?php foreach($this->aauth->get_user_groups() as $row): ?>
                            <li><a href="#"><i class="fa fa-chevron-right"></i> <?= _ent($row->name); ?></a></li>
                           <?php endforeach; ?>
                          </ul>
                        </div>
                      </div>
                      <!-- /.widget-user -->
                    </div>

                     <div class="col-md-6">
                      <!-- Widget: user widget style 1 -->
                      <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="">
						<br>
                          <h3 style="color: white;"> &nbsp;&nbsp;User Information</h3>
						  <br>
                        </div>
                        <div class="box-footer no-padding">
                          <ul class="nav nav-stacked">
                            <li><a href="#"><i class='fa fa-shield color-orange'></i> Status 
                              <?php if ($user->banned) :?>
                                <span class="pull-right badge bg-red">Banned</span></a>
                              <?php else: ?>
                                <span class="pull-right badge bg-blue">Active</span></a>
                              <?php endif; ?>
                            </li>
                            <li><a href="#"><i class='fa  fa-safari  color-orange'></i> Last Login <span class="pull-right "><?= _ent($user->last_login); ?></span></a></li>
                            <li><a href="#"><i class='fa fa-history color-orange'></i> Last Activity <span class="pull-right "><?= _ent($user->last_activity); ?></span></a></li>
                            <li><a href="#"><i class='fa fa-calendar-check-o  color-orange'></i> Date Created <span class="pull-right "><?= _ent($user->date_created); ?></span></a></li>
                            <li><a href="#"><i class='fa fa-chrome color-orange'></i> IP Address <span class="pull-right "><?= _ent($user->ip_address); ?></span></a></li>
                          </ul>
                        </div>
                      </div>
                      <!-- /.widget-user -->
                    </div>
                   <div class="row-fluid col-md-12" >
                        <?php is_allowed('user_update_profile', function() use ($user){?>
                        <a class="btn btn-flat btn-info btn-warning btn_edit btn_action" id="btn_edit" data-stype='back' title="edit profile (Ctrl+e)" href="<?= site_url('administrator/user/edit_profile/'.$user->id); ?>"><i class="fa fa-edit" ></i> Edit Profile</a>
                        <?php }) ?>
                  </div>

                 
            </div><br>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
