<style>
.form-control:focus {
    box-shadow: 0 0 0 2pt rgb(255 255 255 / 50%) !important;
    border-radius: 5px !important;
}
.content-wrapper,   .main-footer {
     
   
    background-image: url(../../../cc-content/themes/cicool/asset/img/header2.jpg);
}


.row {
    margin-right: 15%;
    margin-left: 17%;
}
 

 .box-footer {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
    border-bottom-right-radius: 3px;
    border-bottom-left-radius: 3px;
    border-top: 0px solid #f4f4f4;
    padding: 43px;
    background-color: #ffffff;
}

 
body {
    font-family: "Helvetica Neue",Helvetica,Arial,sans-serif;
    font-size: 17px;
    line-height: 1.42857143;
    color: #ffffffe0;
    background-color: #fff;
}


.btn.btn-flat {
    border-radius: 0;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    border-width: 0px;
}


.btn, .chosen-container .chosen-single, .chosen-container .chosen-choices {
    border-radius: 0px !important;
}

.col-md-7 {
    width: 62.333333%;
}

.btn {
    display: inline-block;
    padding: 13px 30px;
    margin-bottom: 0;
    font-size: 14px;
    font-weight: 800;
    line-height: 1.42857143;
    text-align: center;
    white-space: nowrap;
    vertical-align: middle;
    -ms-touch-action: manipulation;
    touch-action: manipulation;
    cursor: pointer;
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    background-image: none;
    border: 1px solid transparent;
    border-radius: 4px;
}
.box {
    position: relative;
    border-radius: 0px;
    background: rgb(255 255 255 / 0%);
    border-top: 0px solid #d2d6de;
    margin-bottom: 20px;
    width: 100%;
    box-shadow: 0 1px 1px rgb(0 0 0 / 10%);
}
 .form-control {
    display: block;
    width: 100%;
    height: 50px;
    padding: 6px 12px;
    font-size: 17px;
	font-weight: 700;
    line-height: 1.42857143;
    color: #fff;
    background-color: rgb(255 255 255 / 20%);
    background-image: none;
    border: 0px solid #ccc;}
 
.form-control {
    border-color: #DEDCDC !important;
    border-radius: 0px !important;
}
.content-wrapper,   .main-footer {
     
    
 .box {
    position: relative;
    border-radius: 3px;
    background: rgba(0, 0, 0, 0);
    border-top: 0px solid #d2d6de;
    margin-bottom: 20px;
    width: 100%;
    box-shadow: 0 1px 1px rgb(0 0 0 / 10%);
}
 




.chosen-container-single .chosen-single {
    position: relative;
    display: block;
    overflow: hidden;
    padding: 11px 0 0 20px;
    height: 45px;
    border: 0px solid #d2d6de;
    background-color: rgb(255 255 255 / 20%);
    background-clip: padding-box;
    color: #fff;
    text-decoration: none;
    white-space: nowrap;
    line-height: 24px;
font-weight: 800;
}


  

</style>
<script src="<?= BASE_ASSET; ?>/js/jquery.hotkeys.js"></script>
<script type="text/javascript">
//This page is a result of an autogenerated content made by running test.html with firefox.
function domo(){
 
   // Binding keys
   $('*').bind('keydown', 'Ctrl+e', function assets() {
      $('#btn_edit').trigger('click');
       return false;
   });

   $('*').bind('keydown', 'Ctrl+x', function assets() {
      window.location.href = BASE_URL + '/administrator/user';
       return false;
   });
}

jQuery(document).ready(domo);
</script>
<style type="text/css">
  .widget-user-header {
    padding-left: 20px !important; 
  }
</style>
<!-- Content Header (Page header) -->
<!--
<section class="content-header">
   <h1>
      <?= cclang('user'); ?>
      <small><?= cclang('detail', cclang('user')); ?></small>
   </h1>
   <ol class="breadcrumb">
      <li><a href="#"><i class="fa fa-dashboard"></i> <?= cclang('home'); ?></a></li>
      <li class=""><a  href="<?= site_url('administrator/user'); ?>"><?= cclang('user'); ?></a></li>
      <li class="active"><?= cclang('detail'); ?></li>
   </ol>
</section> -->
<!-- Main content -->
<br><br>
<section class="content">
   <div class="row" >
     
      <div class="col-md-7">
         <div class="box box-warning">
            <div class="box-body ">

                      <!-- /.col -->
                  <div class="col-md-12">
                    <!-- Widget: user widget style 1 -->
                    <div class="box box-widget widget-user">
                      <!-- Add the bg color to the header using any of the bg-* classes -->
                      <div class="widget-user-header " style="background-color: white">
                        <h3 class="widget-user-username text-black"><?= _ent(ucwords($user->full_name)); ?></h3>
                        <h5 class="widget-user-desc text-black"><?= _ent($user->username); ?></h5>
                      </div>
                      <div class="widget-user-image">
                        <img class="img-circle" src="<?= BASE_URL.'uploads/user/'.(!empty($user->avatar) ? $user->avatar :'default.png'); ?>" alt="User Avatar" style="height: 80px; width: 80px" >
                      </div>
                      <div class="box-footer">
                       
                        <!-- /.row -->
                      </div>
                    </div>     
                    </div>
                    <div class="col-md-6">
                      <!-- Widget: user widget style 1 -->
                      <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="">
                          
                          <h3 class=""><?= cclang('group', cclang('user')); ?></h3>
                        </div>
                        <div class="box-footer no-padding">
                          <ul class="nav nav-stacked">
                          <?php foreach($this->aauth->get_user_groups($user->id) as $row): ?>
                            <li><a href="#"><i class="fa fa-chevron-right"></i> <?= $row->name; ?></a></li>
                           <?php endforeach; ?>
                          </ul>
                        </div>
                      </div>
                      <!-- /.widget-user -->
                    </div>

                     <div class="col-md-6">
                      <!-- Widget: user widget style 1 -->
                      <div class="box box-widget widget-user-2">
                        <!-- Add the bg color to the header using any of the bg-* classes -->
                        <div class="">
                          <h3 class=""><?= cclang('detail', cclang('user')); ?></h3>
                        </div>
                        <div class="box-footer no-padding">
                          <ul class="nav nav-stacked">
                            <li><a href="#"><i class='fa fa-shield color-orange'></i> <?= cclang('status'); ?> 
                              <?php if ($user->banned) :?>
                                <span class="pull-right badge bg-red"><?= cclang('banned'); ?></span></a>
                              <?php else: ?>
                                <span class="pull-right badge bg-blue"><?= cclang('active'); ?></span></a>
                              <?php endif; ?>
                            </li>
                            <li><a href="#"><i class='fa  fa-safari  color-orange'></i> <?= cclang('last_login'); ?> <span class="pull-right "><?= _ent($user->last_login); ?></span></a></li>
                            <li><a href="#"><i class='fa fa-history color-orange'></i> <?= cclang('last_activity'); ?> <span class="pull-right "><?= _ent($user->last_activity); ?></span></a></li>
                            <li><a href="#"><i class='fa fa-calendar-check-o  color-orange'></i> <?= cclang('date_created'); ?> <span class="pull-right "><?= _ent($user->date_created); ?></span></a></li>
                            <li><a href="#"><i class='fa fa-chrome color-orange'></i> <?= cclang('ip_address'); ?> <span class="pull-right "><?= _ent($user->ip_address); ?></span></a></li>
                          </ul>
                        </div>
                      </div>
                      <!-- /.widget-user -->
                    </div>
                   <div class="row-fluid col-md-12" >
                        <a class="btn btn-flat btn-default btn_action" id="btn_back" title="back (Ctrl+x)" href="<?= site_url('administrator/user/'); ?>"><i class="fa fa-undo" ></i> <?= cclang('go_list', cclang('user')); ?></a>
                        <?php is_allowed('user_update', function() use ($user){?>
                        <a class="btn btn-flat btn-info btn-warning btn_edit btn_action" id="btn_edit" data-stype='back' title="edit user (Ctrl+e)" href="<?= site_url('administrator/user/edit/'.$user->id); ?>"><i class="fa fa-edit" ></i> <?= cclang('update', cclang('user')); ?></a>
                        <?php }) ?>
                  </div>
            </div>
            <!--/box body -->
         </div>
         <!--/box -->

      </div>
   </div>
</section>
<!-- /.content -->
